### ISSUE TITLE
problem applying patches. 

### ISSUE THREAD

**Issue by shorkoLdt** [arduino/openwrt-yun-1505#3]
After manually downloading the opkg 3.1 release, work around for the other problem of getting the file from opkg, and putting it in the dl folder and installation continued until the problem below. 

Applying ./patches/001-ship-pkg-m4.patch using plaintext: 
patching file m4/pkg.m4
can't find file to patch at input line 163
Perhaps you used the wrong -p or --strip option?
## The text leading up to this was:

|--- a/Makefile.am
## |+++ b/Makefile.am

No file to patch.  Skipping patch.
1 out of 1 hunk ignored
Patch failed!  Please fix ./patches/001-ship-pkg-m4.patch!
make[3]: **\* [/home/shortie/Desktop/dave/toolChains/openwrt-yun-master/build_dir/host/opkg-618/.prepared420b5453227a16877d986c58b99db53c] Error 1
make[3]: Leaving directory `/home/shortie/Desktop/dave/toolChains/openwrt-yun-master/package/opkg'
make[2]: *** [package/opkg/host/compile] Error 2
make[2]: Leaving directory`/home/shortie/Desktop/dave/toolChains/openwrt-yun-master'
make[1]: **\* [/home/shortie/Desktop/dave/toolChains/openwrt-yun-master/staging_dir/target-mips_r2_uClibc-0.9.33.2/stamp/.package_compile] Error 2
make[1]: Leaving directory `/home/shortie/Desktop/dave/toolChains/openwrt-yun-master'
make: **\* [world] Error 2

hope this helps again.

Thanks
Regards
Mike

**Comment by facchinm** [comment]
Keeping track of this issue in #2 , closing as "duplicate"
